### PR TITLE
PigeonMaps & Nominatim

### PR DESCRIPTION
**Pull request by diogohmcruz**
Mapas no Service, Crowdfunding, createServices e createCrowdfunding.

### CODE REVIEW

**Review by Evenilink — CHANGES_REQUESTED** [review]
2 things:
- When you scroll down, if you try to click, the selected point is not where your mouse is.
- There should also be a map for when you register.

**Comment by Evenilink** [comment]
The map should replace the current Country/Region/City during the Sign Up.

**Comment by diogohmcruz** [comment]
@Evenilink 
- acho que o ponto 1 da review está relacionado com este issue: https://github.com/mariusandra/pigeon-maps/issues/2
- de certeza que o po quer isso?

**Comment by diogohmcruz** [comment]
@Evenilink resolvi o problema do scroll usando um modal.

**Comment by diogohmcruz** [comment]
@Evenilink já resolvi.

**Comment by Evenilink** [comment]
- Good work on the signup page.
- My modal is not centered, and I also can't see it all.
- Maybe instead of a modal, it's better to just show the map always?
- With a big location name, in the pages that location is displayed, it's just too big. For example, if you select FEUP, the location is displayed as "Faculdade de Engenharia da Universidade do Porto, s/n, Rua Doutor Roberto Frias, Paranhos, Porto, Área Metropolitana do Porto, Norte, 4200-465, Portugal". It would be better if it could just say Paranhos or Porto.

**Review by Evenilink — APPROVED** [review]

**Pull request merged**
